# Generated by Django 5.1.6 on 2025-02-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
