# Generated by Django 5.1.6 on 2025-02-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='DOB',
            new_name='date_of_birth',
        ),
    ]
